MoneyManager/MoneyManager.Web/Controllers/BudgetCategoryController.cs
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using MoneyManager.Core.Interfaces.Factories;
using MoneyManager.Core.Interfaces.Managers;
using MoneyManager.Core.Models.Budgets;
using MoneyManager.Core.Requests;

namespace MoneyManager.Web.Controllers
{
    public class BudgetCategoryController : Controller
    {
	    private readonly IRequest<BudgetCategoryModel, BudgetCategoryModel> _createRequest;

        public BudgetCategoryController(IRequest<BudgetCategoryModel, BudgetCategoryModel> createRequest)
        {
	        _createRequest = createRequest;
        }

        [HttpPost]
        public async Task<ActionResult> Create(BudgetCategoryModel model)
        {
	        if (!ModelState.IsValid)
		        return PartialView("../Budget/Pop-up Forms/CreateCategoryForm");

            model = await _createRequest.ExecuteAsync(model);

	        return Json(new
	        {
		        attachAfter = $"tr.budget-group-row[data-group-id='{model.BudgetGroupId}']",
		        view = this.RenderPartialView("../Budget/BudgetTable/CategoryRow", model)
	        });
		}
    }
}

MoneyManager/MoneyManager.Web/Controllers/BudgetController.cs
using System.Collections.Generic;
using System.Data.Entity.ModelConfiguration;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using MoneyManager.Common.Managers.Identity;
using MoneyManager.Core.Entities;
using MoneyManager.Core.Interfaces.Factories;
using MoneyManager.Core.Interfaces.Managers;
using MoneyManager.Core.Interfaces.Service;
using MoneyManager.Core.Models;
using MoneyManager.Core.Models.Budgets;
using MoneyManager.Core.Requests;

namespace MoneyManager.Web.Controllers
{
    [Authorize]
    public class BudgetController : Controller
    {
	    private readonly IRequest<BudgetModel, int?, Task<ApplicationUser>> _getRequest;
	    private readonly IRequest<BudgetModel, BudgetModel, Task<ApplicationUser>> _createRequest;
	    private readonly IRequest<IEnumerable<BudgetModel>, int, Task<ApplicationUser>> _openRequest;
	    private readonly IRequest<bool, int, Task<ApplicationUser>> _deleteRequest;
	    private readonly IRequest<BudgetModel, int, string, Task<ApplicationUser>> _updateNameRequest;
	    private UserManager<ApplicationUser> _userManager;

        public BudgetController(
	        IRequest<BudgetModel, int?, Task<ApplicationUser>> getRequest,
	        IRequest<BudgetModel, BudgetModel, Task<ApplicationUser>> createRequest,
			IRequest<IEnumerable<BudgetModel>, int, Task<ApplicationUser>> openRequest,
	        IRequest<bool, int, Task<ApplicationUser>> deleteRequest,
			IRequest<BudgetModel, int, string, Task<ApplicationUser>> updateNameRequest)
            : this(getRequest, createRequest, openRequest, deleteRequest, updateNameRequest, null)
        {}
        public BudgetController(
			IRequest<BudgetModel, int?, Task<ApplicationUser>> getRequest,
			IRequest<BudgetModel, BudgetModel, Task<ApplicationUser>> createRequest,
			IRequest<IEnumerable<BudgetModel>, int, Task<ApplicationUser>> openRequest,
	        IRequest<bool, int, Task<ApplicationUser>> deleteRequest,
			IRequest<BudgetModel, int, string, Task<ApplicationUser>> updateNameRequest,
			UserManager<ApplicationUser> userManager)
        {
	        _getRequest = getRequest;
	        _createRequest = createRequest;
	        _openRequest = openRequest;
	        _deleteRequest = deleteRequest;
	        _updateNameRequest = updateNameRequest;
	        _userManager = userManager;
        }

	    private UserManager<ApplicationUser> UserManager => 
			_userManager ?? (_userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>());

	    [HttpGet]
        public async Task<ActionResult> Index(int? id = null)
        {
            if (User == null)
                return RedirectToAction("Login", "Account");

            var budget = await _getRequest.ExecuteAsync(id, AppUser);

			if (budget == null)
                return RedirectToAction("Open");

			return View(budget);
        }

		[HttpPost]
        public async Task<ActionResult> Create(BudgetModel budgetModel)
        {
            if (User == null)
                return RedirectToAction("Login", "Account");

            if (!ModelState.IsValid)
                return PartialView("Forms/CreateBudgetForm");

            budgetModel = await _createRequest.ExecuteAsync(budgetModel, AppUser);

			return RedirectToAction("Index", new { id = budgetModel.Id });
        }

        [HttpGet]
        public async Task<ActionResult> Open()
        {
	        var budgets = await _openRequest.ExecuteAsync(10, AppUser);

			return View(budgets);
        }

        [HttpDelete]
        public async Task<ActionResult> Delete(int id)
        {
	        await _deleteRequest.ExecuteAsync(id, AppUser);
			return Json(new { returnUrl = Url.Action("Open") });
        }

        [HttpPut]
        public async Task<ActionResult> UpdateName(int id, string name)
        {
            if (User == null)
                return RedirectToAction("Login", "Account");

            if (string.IsNullOrEmpty(name))
				return PartialView("Pop-up Forms/EditBudgetNameForm");

	        var resultModel = await _updateNameRequest.ExecuteAsync(id, name, AppUser);

			return Json(new {returnUrl = Url.Action("Index", new {id = resultModel.Id})});
        }

        private Task<ApplicationUser> AppUser
        {
            get
            {
                if (User == null) return Task.FromResult<ApplicationUser>(null);
                return UserManager.FindByNameAsync(User.Identity.Name);
            }
        }
    }
}

MoneyManager/MoneyManager.Web/Controllers/BudgetGroupController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Web.Mvc;
using MoneyManager.Core.Interfaces.Factories;
using MoneyManager.Core.Interfaces.Managers;
using MoneyManager.Core.Models.Budgets;
using MoneyManager.Core.Requests;

namespace MoneyManager.Web.Controllers
{
    [Authorize]
    public class BudgetGroupController : Controller
    {
	    private readonly IRequest<BudgetGroupModel, BudgetGroupModel> _createRequest;

        public BudgetGroupController(IRequest<BudgetGroupModel, BudgetGroupModel> createRequest)
        {
	        _createRequest = createRequest;
        }

        [HttpPost]
        public async Task<ActionResult> Create(BudgetGroupModel groupModel)
        {
            if(!ModelState.IsValid)
				return PartialView("Error");

            groupModel = await _createRequest.ExecuteAsync(groupModel);

			return Json(new
			{
				attachInsideOf = "#budget-table > table > tbody",
				view = this.RenderPartialView("../Budget/BudgetTable/GroupRow", groupModel)
			});
        }
	}
}

MoneyManager/MoneyManager.Web/Views/Budget/Pop-up Forms/CreateCategoryForm.cshtml
@model MoneyManager.Core.Models.Budgets.BudgetCategoryModel

<tr class="create-category-form">
    <td colspan="6">
        <table>
            <tr>
                <td>
                    @using (Html.BeginForm("Create", "BudgetCategory", FormMethod.Post,
                        new
                        {
                            @class = "ajax-form",
                            role = "form",
                            attach_to = "GroupRow.addCategory",
                            ko_model = "CategoryRow"
                        }))
                    {
                        @Html.HiddenFor(x => x.BudgetGroupId)
                        <div class="form-group">
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <button type="button" data-dismiss="modal" aria-label="Close" class="cancel btn btn-default">Cancel</button>
                            <button type="button" class="submit btn btn-default">Create Category</button>
                        </div>
                    }
                </td>

            </tr>
        </table>
    </td>
</tr>

MoneyManager/MoneyManager.Web/Views/Budget/Pop-up Forms/CreateGroupForm.cshtml
@model MoneyManager.Core.Models.Budgets.BudgetGroupModel

<div class="modal fade" id="create-group-form" tabindex="-1" role="dialog"
     aria-labelledby="create-group-form-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="create-group-form-label">Create a Category Group</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Create", "BudgetGroup", FormMethod.Post,
                new { @class = "ajax-form form-horizontal", role = "form" }))
                {
                    @Html.HiddenFor(x => x.BudgetId)
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, "Group Name:", new { @class = "control-label" })
                        <div class="input">
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                            <div class="validation-error">
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <button type="button" data-dismiss="modal" aria-label="Close" class="cancel btn btn-default">Cancel</button>
                        <button type="button" class="submit btn btn-default">Create Group</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

MoneyManager/MoneyManager.Web/Views/Budget/Pop-up Forms/DeleteBudgetForm.cshtml
@model MoneyManager.Core.Models.Budgets.BudgetModel

<form class="ajax-form form-horizontal" role="form" action=@Url.Action("Delete","Budget") method="delete">
    @Html.HiddenFor(x => x.Id)
    <div class="message">
        <p>Are you sure you want to delete this budget?</p>
        <p><span>This cannot be reversed.</span></p>
        <p>Like, even if you ask nicely.</p>
    </div>
    <div class="action-buttons">
        <button type="button" data-toggle="dropdown" class="dropdown-toggle cancel btn btn-default">Cancel</button>
        <button type="button" class="submit btn btn-primary">Delete</button>
    </div>
</form>

MoneyManager/MoneyManager.Web/Views/Budget/Pop-up Forms/EditBudgetNameForm.cshtml
@model MoneyManager.Core.Models.Budgets.BudgetModel

<form class="ajax-form form-horizontal" role="form" action=@Url.Action("UpdateName","Budget") method="put">
    @Html.HiddenFor(x => x.Id)
    <div class="input form-group">
        @Html.LabelFor(model => model.Name, "Budget Name:", new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.TextBoxFor(model => model.Name, new { Value="", @class = "input-md form-control",
                                                        id = "budget-name-text-input", placeholder = "New Name" })
        </div>
        <div id="budget-name-field-validation">
            @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger validation-error"})
        </div>
    </div>
    <div class="action-buttons">
        <button type="button" data-toggle="dropdown" class="dropdown-toggle cancel btn btn-default">Cancel</button>
        <button type="button" class="submit btn btn-primary">Submit</button>
    </div>
</form>